/**:
    ros__parameters:
      # This video device may change when devices are unplugged or restarted
      # camera paths must be found using the commands provided
      video_device: "/dev/video0"
      #pixel_format: "YUVU"
      #output_encoding: "MJPG"
      #image_size: [640,480]
 # .image_raw.jpeg_quality: "50"
